name: CI Ubuntu 24.04 Playwright Fix

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # Aqui indicamos que o runner deve ser o Ubuntu 24.04 oficial
    runs-on: ubuntu-24.04

    steps:
      # 1) Faz checkout do código do repositório
      - name: Checkout code
        uses: actions/checkout@v4

      # 2) Exibe a versão do Ubuntu (útil para debug)
      - name: Mostrar versão do Ubuntu
        run: cat /etc/os-release

      # 3) Instala as dependências do sistema
      - name: Instalar dependências do sistema (Ubuntu 24.04)
        run: |
          # Atualiza o índice de pacotes do APT
          sudo apt-get update

          # Instala pacotes necessários para rodar browsers/headless, etc.
          # Note que substituímos 'libasound2' por 'libasound2t64'
          sudo apt-get install -y \
            wget \
            unzip \
            curl \
            gnupg \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libnss3 \
            libxcomposite1 \
            libxdamage1 \
            libxrandr2 \
            libxss1 \
            libgtk-3-0t64 \
            libasound2t64 \
            libatk1.0-0t64 \
            libatk-bridge2.0-0t64 \
            libdrm2 \
            libdbus-1-3 \
            libxfixes3 \
            libxcursor1 \
            libxt6 \
            libcups2t64

          # Baixa o pacote .deb do Google Chrome
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb

          # Instala o Chrome. Se faltar dependência, o apt corrige com -f
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      # 4) Configura o Python 3.10
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 5) Instala as dependências Python do seu requirements.txt
      - name: Install dependencies Python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 6) Instala os navegadores do Playwright com suas dependências
      - name: Install Playwright Browsers
        run: |
          npx playwright install --with-deps

      # 7) Executa seus testes (por exemplo, pytest)
      - name: Run tests
        run: |
          pytest || echo "Tests falharam"
