name: Coletar HSM Incremental

on:
  workflow_dispatch:
  schedule:
    - cron: '0 3-17 * * *'

jobs:
  run_coletar_token:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0t64 \
            libgtk-3-0t64 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libxtst6 \
            xauth \
            xvfb

      - name: Install Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run token collection script
        run: python coletar_token.py
        env:
          EMAIL_HIPLAT: ${{ secrets.EMAIL_HIPLAT }}
          SENHA_HIPLAT: ${{ secrets.SENHA_HIPLAT }}
          RELATORIO_URL: ${{ secrets.RELATORIO_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}

  run_coletar_hsm:
    runs-on: ubuntu-24.04
    needs: run_coletar_token
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libgtk2.0-0t64 \
            libgtk-3-0t64 \
            libgbm-dev \
            libnotify-dev \
            libnss3 \
            libxss1 \
            libasound2t64 \
            libxtst6 \
            xauth \
            xvfb

      - name: Install Chrome
        run: |
          wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y

      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt

      - name: Run HSM incremental script
        run: python coletar_hsm_incremental.py
        env:
          EMAIL_HIPLAT: ${{ secrets.EMAIL_HIPLAT }}
          SENHA_HIPLAT: ${{ secrets.SENHA_HIPLAT }}
          RELATORIO_URL: ${{ secrets.RELATORIO_URL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
