name: Capturar Token Automático

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'  # Executa de hora em hora

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install selenium webdriver-manager

    - name: Rodar o Script
      run: |
        python coletar_token.py

    - name: Fazer commit do novo token
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions Bot"
        git remote set-url origin https://x-access-token:${GH_TOKEN}@github.com/${{ github.repository }}

        git add token.txt
        git diff --staged --quiet && echo "📭 Sem mudanças no token. Nada para commitar." && exit 0

        git commit -m "Token atualizado automaticamente"
        git push origin main
