name: Capturar Token Automático

on:
  schedule:
    - cron: '0 * * * *'  # Roda de hora em hora (posso ensinar mudar depois!)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install selenium webdriver-manager

    - name: Rodar o Script para Capturar Token
      run: |
        python coletar_token.py
      env:
        EMAIL_HIPLAT: ${{ secrets.EMAIL_HIPLAT }}
        SENHA_HIPLAT: ${{ secrets.SENHA_HIPLAT }}

    - name: Fazer commit do novo token
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add token.txt
        git commit -m "Atualizar token automático"
        git push
