name: Coletar Token e Salvar no Supabase

on:
  schedule:
    - cron: "0 * * * *"  # roda a cada hora
  workflow_dispatch:     # permite rodar manualmente

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
      SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
      SUPABASE_BUCKET: ${{ secrets.SUPABASE_BUCKET }}
      SUPABASE_TABLE_NAME: ${{ secrets.SUPABASE_TABLE_NAME }}
      EMAIL_HIPLAT: ${{ secrets.EMAIL_HIPLAT }}
      SENHA_HIPLAT: ${{ secrets.SENHA_HIPLAT }}
      RELATORIO_URL: ${{ secrets.RELATORIO_URL }}

    steps:
      - name: 📥 Checkout do repositório
        uses: actions/checkout@v3

      - name: 🐍 Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 🔧 Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 🧪 Executar script
        run: python seu_script.py
