name: Capturar Token Automático

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar o repositório
      uses: actions/checkout@v3

    - name: Configurar o Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Instalar dependências
      run: |
        pip install selenium webdriver-manager

    - name: Rodar o Script
      run: |
        python coletar_token.py

    - name: Fazer commit do novo token
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions Bot"
        git add token.txt
        git commit -m "Token atualizado automaticamente"
        git push
